spring.application.name=servlet-vs-reactive

## THREADS

# reactor - thread config
#reactor.netty.ioWorkerCount=1
#reactor.netty.ioSelectCount=1
#reactor.netty.pool.maxConnections=3


# tomcat - thread config
#server.tomcat.threads.max=2
#server.tomcat.threads.min-spare=1
##server.tomcat.threads.max-queue-capacity=2
##server.tomcat.max-connections=2

# Virtual Threads
#spring.threads.virtual.enabled=true


## HUGE FILE TIMEOUT

# Alternativively use DifferedRequest, set it to -1 to be open indefinitely until the client closes
#spring.mvc.async.request-timeout=-1
# This is for keep-alive header - only for normal calls (check this) - doesn't care for async calls and only for tomcat
# server.tomcat.keep-alive-timeout=5000

## OBSERVABILITY

#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

#management.tracing.enabled= true
#management.tracing.sampling.probability=  1.0
