server:
  port: 8081

spring:
  # connection info to connect to the DB
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/shopit?schema=public
    username: postgres
    password: test
  # tells the jpa to use hibernate to create/update tables to match with the code schema
  jpa:
    hibernate:
      ddl-auto: update